name: Build and publish docker image

on: workflow_dispatch

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish image
        run: |
          docker build . --tag ghcr.io/larsensolutions/domeneshop-bot:latest
          docker push ghcr.io/larsensolutions/domeneshop-bot:latest
